import { DocsShell } from "@/components/docs/DocsShell";
import styles from "../docs.module.css";

export const metadata = { title: "Facts inventory — mcpfor.work docs" };

export default function FactsInventoryPage() {
  return (
    <DocsShell
      slug="/docs/facts-inventory"
      title="Facts inventory"
      lead="The facts inventory is the honesty engine. It's the only source a draft may claim from — so your AI never invents a credential you don't have."
      toc={[
        { id: "what", label: "What it is" },
        { id: "coverage", label: "ATS coverage check" },
        { id: "gaps", label: "Gaps, not keyword stuffing" },
      ]}
    >
      <section className={styles.section} id="what">
        <h2 className={styles.h2}>What it is</h2>
        <p className={styles.p}>
          Every draft is generated by your own client from a structured brief. That brief carries a
          facts inventory — each item traced to a source: your CV, an achievement from your bank, or
          a confirmed answer you gave. The model may phrase those facts for the role, but it may not
          claim anything outside the card.
        </p>
        <div className="term">
          <div className="term__bar">
            <span>facts inventory</span>
          </div>
          <div className="term__body">
            <div>6 years ICU, Hospital La Paz (Madrid) &nbsp;<span className="p">— CV</span></div>
            <div>Cut ventilator-associated events 23% &nbsp;<span className="p">— Achievement #2</span></div>
            <div>NMBI registration in progress &nbsp;<span className="p">— Confirmed answer</span></div>
          </div>
        </div>
      </section>

      <section className={styles.section} id="coverage">
        <h2 className={styles.h2}>ATS coverage check</h2>
        <p className={styles.p}>
          Before you submit, a deterministic check (no LLM) compares the posting&rsquo;s keywords to
          your draft and classifies each: <strong style={{ fontWeight: 600 }}>covered</strong>, a{" "}
          <strong style={{ fontWeight: 600 }}>synonym</strong> you can align, something you{" "}
          <strong style={{ fontWeight: 600 }}>have but didn&rsquo;t mention</strong>, or a{" "}
          <strong style={{ fontWeight: 600 }}>genuine gap</strong>. It tells you where you&rsquo;re
          strong and where you truly aren&rsquo;t.
        </p>
      </section>

      <section className={styles.section} id="gaps">
        <h2 className={styles.h2}>Gaps, not keyword stuffing</h2>
        <div className={styles.note}>
          <span className={styles.noteLabel}>Never fabricate</span>
          <span className={styles.noteBody}>
            A genuine gap is acknowledged, never stuffed. If a role wants paediatric ICU and you
            don&rsquo;t have it, the draft won&rsquo;t claim it — it leans on what you&rsquo;ve
            proven instead. Honesty is structural, not a setting.
          </span>
        </div>
      </section>
    </DocsShell>
  );
}
